export const UPDATE_UNIVERSITIES: Symbol = Symbol('UPDATE_UNIVERSITIES');
export const UPDATE_FAVORITE_UNIVERSITIES: Symbol = Symbol(
  'UPDATE_FAVORITE_UNIVERSITIES',
);
export const UPDATE_FAVORITE_UNIVERSITY: Symbol = Symbol(
  'UPDATE_FAVORITE_UNIVERSITY',
);
export const UPDATE_CURRENT_UNIVERSITY: Symbol = Symbol(
  'UPDATE_CURRENT_UNIVERSITY',
);
